project_id = "abzngybgfxqpcperxgqz"

[functions.analyze-text]
verify_jwt = false

[functions.send-fraud-alert]
verify_jwt = true

[functions.transcribe-audio]
verify_jwt = true

[functions.analyze-call]
verify_jwt = true

[functions.analyze-caller]
verify_jwt = true
